---
kind: pipeline
type: docker
name: push

platform:
  os: linux
  arch: amd64

steps:
  - name: docker-push
    image: plugins/docker
    settings:
      repo: polygonio/swagger-cli
      tag:
        - ${DRONE_BRANCH/master/latest}
        - ${DRONE_COMMIT}

trigger:
  branch:
    - master
  event:
    - push
...
